name: generate-iteration-report

on: [push]

env:
  GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
  GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
  ZENHUB_API_TOKEN: ${{ secrets.ZENHUB_API_TOKEN }}

jobs:
  generate-iteration-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        ref: ${{ github.head_ref }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate release JSON
      run: python .github/releases.py

    - name: Grab any new issues and save to CSV
      run: python .github/get_issues.py

    - name: Update iteration summary JSON
      run: python .github/summarize_iterations.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "Automatic update from GitHub Actions"
        add: "data/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_API_TOKEN }}
        branch: 'feature/data-workflow'
