name: github pages
# run on develop and push the built hugo site to master
# (Currently User/Org pages must be built from the master branch.)

on:
  push:
    branches:
    - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod

    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.2'
        extended: true

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install npm dependencies
      run: npm ci

    - name: build site
      run: hugo --minify

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
