name: iteration report

on:
  schedule:
    # run at 4:15am on Saturdays
    - cron:  '15 4 * * SAT'

env:
  GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
  GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
  ZENHUB_API_TOKEN: ${{ secrets.ZENHUB_API_TOKEN }}

jobs:
  iteration-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        ref: ${{ github.head_ref }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Summarize iteration activity and update iteration data file
      run: python .github/summarize_iterations.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "Update iteration summary data from GitHub Actions"
        add: "data/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GH_API_TOKEN }}
        branch: ${{ github.ref }}


